# Generated by Django 5.0 on 2023-12-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_img_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rules',
        ),
    ]
