# Generated by Django 5.0 on 2023-12-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_event_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhead',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
