# Generated by Django 5.0 on 2024-02-10 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField(max_length=200, null=True)),
                ('venue', models.CharField(max_length=200, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fill', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, default='logo.png', null=True, upload_to='images')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='eventHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('contact', models.BigIntegerField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturals.event')),
            ],
        ),
        migrations.CreateModel(
            name='GSigned',
            fields=[
                ('moodle_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('pname', models.CharField(blank=True, max_length=200)),
                ('contact', models.BigIntegerField(null=True)),
                ('dept', models.CharField(max_length=6, null=True)),
                ('year', models.CharField(max_length=6, null=True)),
                ('scanned', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BigIntegerField(null=True)),
                ('dept', models.CharField(max_length=6, null=True)),
                ('year', models.CharField(max_length=6, null=True)),
                ('pnsme', models.CharField(blank=True, max_length=200)),
                ('ename', models.CharField(max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturals.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
