# Generated by Django 5.0 on 2024-02-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culturals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signed',
            old_name='pnsme',
            new_name='pname',
        ),
    ]
